version: 2.1
#orbs:
#  codecov: codecov/codecov@1.0.5
#docker-workflow:
jobs:
  build:
    docker:
      - image: cimg/rust:1.75.0

    environment:
      # Set your codecov token if your repository is private.
      CODECOV_TOKEN: "ab1ebf03-ceaa-44e5-a5c3-991540225856"
      TZ: "/usr/share/zoneinfo/Europe/Paris"

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Stable Build
          command: |
            cargo build
      - run:
          name: Test
          command: cargo test --verbose --jobs 1 --all
      - run:
          name: Upload Coverage
          command: |
            .scripts/codecov.sh
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

  publish-docker-latest:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - setup_remote_docker:
          version: default 
      - checkout
      - run:
          name: Create the Multi Arch build structure
          command: |
            docker context create multi-arch-context
            docker buildx create --use multi-arch-context
      - run:
          name: Docker build and push
          no_output_timeout: 1.5h
          command: |
            echo `git describe --tags --exact-match` > /tmp/version.txt
            TAG=$(cat /tmp/version.txt)
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            #docker buildx build --platform=linux/amd64,linux/arm64 --push \
            docker buildx build --platform=linux/amd64 --push \
              --progress=plain\
              -t spectare/fakeidp:latest \
              --build-arg VERSION=$(cat /tmp/version.txt) \
              --build-arg COMMITID=${CIRCLE_SHA1} \
              .

  publish-docker-release:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: default 
      - run:
          name: Create the Multi Arch build structure
          command: |
            docker context create multi-arch-context
            docker buildx create --use multi-arch-context --name multi-arch-builder
      - run:
          name: Docker build and push
          command: |
            echo `git describe --tags --exact-match` > /tmp/version.txt
            TAG=$(cat /tmp/version.txt)
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            #docker buildx build --platform=linux/arm64,linux/amd64 --push \
            docker buildx build --platform=linux/amd64 --push \
              --progress=plain\
              -t spectare/fakeidp:$TAG \
              -t spectare/fakeidp:latest \
              --build-arg VERSION=$(cat /tmp/version.txt) \
              --build-arg COMMITID=${CIRCLE_SHA1} \
              .

workflows:
  version: 2
  ci:
    jobs:
      - build
      - publish-docker-latest:
          context: DOCKER
          requires:
            - build
          filters:
            branches:
              only: main
      - publish-docker-release:
          context: DOCKER
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
